spring.application.name=ms-pacientes
server.port=8081

# --- Conexión Oracle Cloud ---
# El uso de la variable ${RUTA_WALLET} es ideal para la portabilidad en la nube
spring.datasource.url=jdbc:oracle:thin:@nexushealthdb_high?TNS_ADMIN=${RUTA_WALLET}
spring.datasource.username=user_Alan
spring.datasource.password=Nexus.Alan_1412
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# --- JPA / Hibernate ---
# Muestra las consultas SQL en consola (Requisito para debug en defensa) [cite: 517]
spring.jpa.show-sql=true
# Formatea el SQL para que sea legible en los logs de la consola
spring.jpa.properties.hibernate.format_sql=true

# Estrategia de validación: garantiza que el esquema SQL y las Entities sean coherentes [cite: 61, 152]
spring.jpa.hibernate.ddl-auto=validate

# Dialecto específico para Oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# --- Estrategia de Nombramiento ---
# Mantiene los nombres de las tablas y columnas tal cual los definiste en @Column [cite: 56]
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl